### ISSUE TITLE
Unable to create terms to charm...

### ISSUE THREAD

**Issue by achittet** [juju/charmstore-client#101]
Hi I am trying to create terms to my charm by following command and its giving the error
charm push-term 
ERROR unrecognized command: charm push-term
@Even i tried installation of charm tools via the snap and they were installed at /snap/bin/charm.
But giving the same ERROR unrecognized command.
@@Below are the juju,charm and ubuntu version using .
Juju version : charm-tools 2.1.9
charm version : 2.0.1-xenial-amd64
Distributor ID: Ubuntu
Description:    Ubuntu 16.04 LTS
Release:        16.04
Codename:       xenial

Can any help to resolve the issue..
Thanks ,
Ankamarao Chitteti.

**Comment by mattyw** [comment]
Hi @achittet,

I'm afraid the docs weren't clear. You will need to install charm-tools v2.2 from the snap store
```
snap install charm
```
If you run the latest (2.2) charm tools from the snap push-term will be available.

I've submitted a fix to the documentation here to make this clearer: https://github.com/juju/docs/pull/1543
