### ISSUE TITLE
xenial/updates to juju/stable breaks command syntax for publish/release

### ISSUE THREAD

**Issue by ryan-beisner** [juju/charmstore-client#104]
Those who automated charm push/publish based on the stable Xenial release, who later need bugfixes, observe breaks in automation when they consume the latest 'stable' charm tool from ppa:juju/stable.

I'm addressing this in the OpenStack Charm CI, but also raising this bug as others may hit the same.

I understand the need to align the tooling syntax, but the abrupt move in a stable tool from `charm publish` to `charm release` breaks users without warning.  If there is an announcement or notice about this change, I've missed it and cannot find it.

```
ubuntu@juju-osci1-machine-8:~$ charm publish
ERROR unrecognized command: charm publish

ubuntu@juju-osci1-machine-8:~$ charm version
charm 2.2.0-0ubuntu1~ubuntu16.04.1~ppa2
charm-tools 2.1.9
ubuntu@juju-osci1-machine-8:~$
```

**Comment by marcoceppi** [comment]
2.2 has been out for quite a long time now. Not sure if there was an
announcement, but I'm adding an alias in charm-tools for release -> publish
with a deprecation notice.
