### ISSUE TITLE
Attempting to push a bundle without a README.md complains about missing metadata.yaml

### ISSUE THREAD

**Issue by jhobbs** [juju/charmstore-client#106]
I tried to push a bundle with only a 'bundle.yaml' in the directory. I got this error:

> jason@inire:~/ciaas-example$ charm push . cs:~jason-hobbs/ciaas-example
ERROR open /home/jason/ciaas-example/metadata.yaml: no such file or directory

Adding a README.md made the error go away.

This is with 2.1.1-0ubuntu1

**Comment by mhilton** [comment]
Closing as a duplicate of #112
