### ISSUE TITLE
'charm' complains about invalid username while it is a valid launchpad id

### ISSUE THREAD

**Issue by dshcherb** [juju/charmstore-client#107]
Hi,

My launchpad id contains a dash at the end (bad idea):
https://launchpad.net/~dima-

Charm login works file. But charm list fails afterwards complaining about an illegal username:

```
charm login
Login to Ubuntu SSO
Press return to select a default value.
E-Mail: <redacted>@<redacted>
Password: 
Two-factor auth (Enter for none): 179402

echo $?
0

charm list
ERROR cannot retrieve identity: cannot fetch groups: GET http://10.25.8.164:8081/v1/u/dima-/groups: cannot unmarshal parameters: cannot unmarshal into field: illegal username "dima-"
```

```
charm list -u "dima-"
ERROR invalid name '"dima-"'

```
```
snap info charm
name:      charm
summary:   "charm and charm-tools"
publisher: charms
description: |
  charmstore-client and charm-tools
commands:
  - charm
tracking:    stable
installed:   2.2 (9) 49MB -
refreshed:   2016-11-15 19:08:20 +0300 MSK
channels:            
  stable:    2.2 (9) 0B -
  candidate: 2.2 (9) 0B -
  beta:      2.2 (7) 0B -
  edge:      2.2 (7) 0B -

```

I should probably change it to something else before it is too late but still.

**Comment by dshcherb** [comment]
Couldn't restrain myself from further testing:

1) charm logout
2) Changed the id to https://launchpad.net/~dmitriis
3) charm login (worked)
charm login 
Login to Ubuntu SSO
Press return to select a default value.
E-Mail: <redacted>
Password: 
Two-factor auth (Enter for none): 098795

4) charm list still fails
charm list
ERROR cannot retrieve identity: cannot fetch groups: GET http://10.25.8.164:8081/v1/u/dima-/groups: cannot unmarshal parameters: cannot unmarshal into field: illegal username "dima-"

**Comment by dshcherb** [comment]
Installed a debian package instead of a snap

```
$ dpkg -l | grep charm-tools
sii  charm-tools                                                 2.1.9-0ubuntu1~ubuntu16.04.1~ppa2                      all          Tools for maintaining Juju charms

```

Straced the charm tool:

```
$ strace -f charm list 2>&1 | grep -i connect
[pid  5718] connect(3, {sa_family=AF_INET, sin_port=htons(53), sin_addr=inet_addr("10.10.10.45")}, 16 <unfinished ...>
[pid  5718] <... connect resumed> )     = 0
[pid  5720] connect(4, {sa_family=AF_INET, sin_port=htons(53), sin_addr=inet_addr("10.10.10.45")}, 16 <unfinished ...>
[pid  5720] <... connect resumed> )     = 0
[pid  5724] connect(3, {sa_family=AF_INET, sin_port=htons(9), sin_addr=inet_addr("162.213.33.121")}, 16) = 0
[pid  5724] connect(3, {sa_family=AF_INET, sin_port=htons(9), sin_addr=inet_addr("162.213.33.122")}, 16) = 0
[pid  5724] connect(3, {sa_family=AF_INET, sin_port=htons(443), sin_addr=inet_addr("162.213.33.121")}, 16) = -1 EINPROGRESS (Operation now in progress)
```

It connected to 162.213.33.121 which is jujucharms.com apparently:

$ nslookup 162.213.33.121
Server:		10.10.10.45
Address:	10.10.10.45#53

Non-authoritative answer:
121.33.213.162.in-addr.arpa	name = jujucharms.com.

Authoritative answers can be found from:
in-addr.arpa	nameserver = a.in-addr-servers.arpa.
in-addr.arpa	nameserver = c.in-addr-servers.arpa.
in-addr.arpa	nameserver = b.in-addr-servers.arpa.
in-addr.arpa	nameserver = d.in-addr-servers.arpa.
in-addr.arpa	nameserver = f.in-addr-servers.arpa.
in-addr.arpa	nameserver = e.in-addr-servers.arpa.
a.in-addr-servers.arpa	internet address = 199.212.0.73
a.in-addr-servers.arpa	has AAAA address 2001:500:13::73
b.in-addr-servers.arpa	internet address = 199.253.183.183
b.in-addr-servers.arpa	has AAAA address 2001:500:87::87
c.in-addr-servers.arpa	internet address = 196.216.169.10
c.in-addr-servers.arpa	has AAAA address 2001:43f8:110::10
d.in-addr-servers.arpa	internet address = 200.10.60.53
d.in-addr-servers.arpa	has AAAA address 2001:13c7:7010::53
e.in-addr-servers.arpa	internet address = 203.119.86.101
e.in-addr-servers.arpa	has AAAA address 2001:dd8:6::101
f.in-addr-servers.arpa	internet address = 193.0.9.1
f.in-addr-servers.arpa	has AAAA address 2001:67c:e0::1

Looks like the error message comes from an internal service (and leaks its address btw) 10.25.8.164 which is rather bad:

$ charm list
ERROR cannot retrieve identity: cannot fetch groups: GET http://10.25.8.164:8081/v1/u/dima-/groups: cannot unmarshal parameters: cannot unmarshal into field: illegal username "dima-"

**Comment by mhilton** [comment]
This is an unfortunate side effect of a number of different behaviors, it is not clear that any particular one is in itself a bug.

1. Charm and launchpad have different ideas about what a valid user name is.
2. Once a user is "registered" with jujucharms.com their username cannot change.
3. Login on the juju command line doesn't notice that the username has changed.

The situation can be recovered however, as you have changed your launchpad username we can update jujucharms.com to use that as your username after which it will work properly.

**Comment by dshcherb** [comment]
Thanks, that should do it for me at least.

JFYI, I created a ticket already (#98941) so any internal updates can be done there.

Something has to be done about this incompatibility and the internal address leakage.

Not sure how hard it would be to change the Charm Store behavior to align with launchpad but the reverse is definitely going to be harder to do.

**Comment by mhilton** [comment]
This particular instance has been resolved.
