### ISSUE TITLE
charm list doesn't take the username as an optional argument 

### ISSUE THREAD

**Issue by mitechie** [juju/charmstore-client#11]
charm list gets my content. 

```
charm list yellow
```

should fetch the work for the yellow team. 

```
charm list yellow bigdata-dev 
```

should fetch the work for the two teams listed and so on, treating the usernames as the nargs of the command.

**Comment by mitechie** [comment]
Currently it requires a -u argument but I don't feel that it should be required in that way.

**Comment by fabricematrat** [comment]
We will provide -u fred,bob but we would like to have the option to do 
charm list name
where name would be a charm name wildcard.
