### ISSUE TITLE
charm logout doesn't remove cached auth data

### ISSUE THREAD

**Issue by anastasiamac** [juju/charmstore-client#115]
Please see https://bugs.launchpad.net/juju/+bug/1665013 for detailed discussion.

**Comment by nskaggs** [comment]
Essentially for the charm command, charm login will prompt for sso information (email, pass, token) the first time. After that, if you charm logout, you can charm login again without being prompted. Removing ~/.go-cookies makes charm login prompt again for sso information. Charm logout should remove all tokens imho.

**Comment by rogpeppe** [comment]
This was fixed in #27 AFAICS.
