### ISSUE TITLE
charm list-resources yaml output breaks fingerprint 

### ISSUE THREAD

**Issue by mitechie** [juju/charmstore-client#134]
charm list-resources cs:~rharding/pgsql-0 --format=yaml
    - name: wal-e
      type: file
      path: wal-e.snap
      description: WAL-E Snap Package
      revision: 0
      fingerprint:
      - 56
      - 176
      - 96
      - 167
      - 81
      - 172
      - 150
      - 56
      - 76
      - 217
      - 50
      - 126
      - 177
      - 177
      - 227
      - 106
      - 33
      - 253
      - 183
      - 17
      - 20
      - 190
      - 7
      - 67
      - 76
      - 12
      - 199
      - 191
      - 99
      - 246
      - 225
      - 218
      - 39
      - 78
      - 222
      - 191
      - 231
      - 111
      - 101
      - 251
      - 213
      - 26
      - 210
      - 241
      - 72
      - 152
      - 185
      - 91
      size: 0

**Comment by fabricematrat** [comment]
Fixed by: https://github.com/juju/charmstore-client/pull/172
