### ISSUE TITLE
charm build fails when LC_ALL not set and locales not installed

### ISSUE THREAD

**Issue by paulgear** [juju/charmstore-client#139]
On a pristine xenial VM, building charms fails unless LC_ALL is explicitly set to the same value as LANG.  See http://pastebin.ubuntu.com/24272995/ for the full session log of an example.

The charm package should behave correctly without setting LC_ALL, or require locales as a dependency.

**Comment by mhilton** [comment]
This is a charm-tools issue, I have raised https://github.com/juju/charm-tools/issues/422 to cover it.
