### ISSUE TITLE
"charm build" includes .swp files in compose charm

### ISSUE THREAD

**Issue by jacekn** [juju/charmstore-client#142]
I have a layer with revision history in git. I have the following line in the .gitignore:
`*.swp`

I edited my charm, checked "git status" and it was clean, I then composed the charm and I ended up with `.prometheus.py.swp` in the composed charm directory.

This is slightly embarrassing but there are situations where behavior like this is be dangerous. It's not uncommon for developers to have `secrets.cfg` stanzas in their .gitignore and keep secrets inside `secrets.cfg`. If "charm build" does not take .gitignore into account the developer can end up pushing secrets to the charmstore.

Could charm tools be improved to catch problems like this?

**Comment by marcoceppi** [comment]
Is this an issue with `charm build`?

**Comment by jacekn** [comment]
@marcoceppi yes I used `charm build` do compose the charm

**Comment by mhilton** [comment]
This is a charm-tools issue I have created https://github.com/juju/charm-tools/issues/421 to cover it
