### ISSUE TITLE
charm whoami dumps teams but it's not clear what it's dumping

### ISSUE THREAD

**Issue by mitechie** [juju/charmstore-client#15]
charm whoami I think should either dump something yaml looking with headers or perhaps use something like juju tabular format with headings for 'username', 'teams'. I think it should also accept the format flag for json/yaml dumps for programmatic access as I think some tools might run a whoami and want to parse the output easily.

**Comment by urosj** [comment]
@mitechie can we start with:

User: john-doe
Group membership: a, b, c, d ...

Adding output flags is ok, but then we need to make that universally available across all charm options, not just to the whoami command. Is that needed?
