### ISSUE TITLE
charm push does not mention the unpublished state of the revision

### ISSUE THREAD

**Issue by mitechie** [juju/charmstore-client#16]
I grabbed my personal charm, made a change, and then repushed it. 

```
% charm push .
cs:~rharding/postgresql-2
```

Now, I know it's unpublished, but there's nothing in the jujucharms.com UI to help me understand that there's a process here to follow. There's only /u/rharding/postgresql/1

We should have output to the unpublished effect that helps lead users along the path through publishing. 

```
% charm push .
url: cs:~rharding/postgresql-2 
channel: unpublished
```

perhaps

**Comment by urosj** [comment]
@mitechie original idea that we had was: 
% charm push .
url: cs:~rharding/postgresql-2 (unpublished) 

But OTOH, push is always unpublished, so this is only useful to a first time user. We need to provide this kind of info to any channel facing command as well.
