### ISSUE TITLE
charm snap failing to build due to go error (overflows int)

### ISSUE THREAD

**Issue by johnsca** [juju/charmstore-client#168]
The charm snap is [failing to build](https://build.snapcraft.io/user/juju/charm-tools/274244) currently due to the following error:

```
# gopkg.in/mgo.v2/bson
gopkg.in/mgo.v2/bson/json.go:320: constant 9007199254740992 overflows int
go install ./github.com/juju/charmstore-client/...
Failed to run 'go install ./github.com/juju/charmstore-client/...' for 'charm': Exited with code 2.
```

**Comment by mhilton** [comment]
This is caused by https://github.com/go-mgo/mgo/issues/310. The best solution is probably to produce a newer release that can be included in the snap.

**Comment by mhilton** [comment]
I have tagged release v2.3.0 and submitted https://github.com/juju/charm-tools/pull/423 to update the charm snap to use it. Hopefully that has resolved this issue.
