### ISSUE TITLE
charm show id doesn't respect the channel given in the argument

### ISSUE THREAD

**Issue by mitechie** [juju/charmstore-client#19]
I ran charm publish --channel=development and now trying to find out how to verify what was done. I tried:

   % charm show -c development cs:~rharding/postgresql id
    id:
      Id: cs:~rharding/postgresql-1
      Name: postgresql
      Revision: 1
      User: rharding

Which is the published version. I just pushed and published revision 2. 

When I do:
    % charm show -c development cs:~rharding/postgresql-2 id 
    id:
      Id: cs:~rharding/postgresql-2
      Name: postgresql
      Revision: 2
      User: rharding

and removing the -c flag

```
% charm show cs:~rharding/postgresql-2 id
id:
   Id: cs:~rharding/postgresql-2
  Name: postgresql
  Revision: 2
  User: rharding
```

There's nothing there that seems to change based on the channel and nothing I can do to verify what channels a revision/id is available in.

**Comment by urosj** [comment]
Need to rerun this to make sure that you've actually published proper revision in development channel.
