### ISSUE TITLE
not able to query extra-bindings from the charm command

### ISSUE THREAD

**Issue by mitechie** [juju/charmstore-client#194]
https://api.jujucharms.com/charmstore/v5/keystone/archive/metadata.yaml

There's nothing in the charm show --list that ties to the extra bindings section of metadata.yaml

**Comment by rogpeppe** [comment]
There are a number of other items in the metadata.yaml that do not have dedicated "show" metadata names. Unless/until we add names for every part of metadata.yaml, you can get the data with something like:

    charm show --format json keystone charm-metadata | jq '."charm-metadata".ExtraBindings'

**Comment by mitechie** [comment]
Ah ok, thanks for the hint/reminder to use charm-metadata. Not sure how I missed that originally.
