### ISSUE TITLE
charm publish without a revision doesn't pick up latest unpublished revision or development revision

### ISSUE THREAD

**Issue by mitechie** [juju/charmstore-client#20]
I expected to be able to do 

```
% charm publish cs:~rharding/postgresql --channel stable
```

That completed without any errors but it did not update the published revision. When I ran charm show id, I got the same revision 1. 

I had to use the revision in the publish command to get it to work

```
% charm publish cs:~rharding/postgresql-2 --channel stable
% charm show cs:~rharding/postgresql id
id:
  Id: cs:~rharding/postgresql-2
  Name: postgresql
  Revision: 2
  User: rharding
```

**Comment by kwmonroe** [comment]
Me too... That is, I also expected 'publish' with no revision to pick the latest pushed revno, or at least tell me what revno it just published.  The current output from a successful 'publish' is nada.

Fwiw, i'm using charm-2.0.0~rc0ubuntu3~ubuntu14.04.1~ppa0.

**Comment by urosj** [comment]
@mitechie @kwmonroe when you say cs:~rharding/postgresql ... that to charm store is resolved to the revision that is pointed by the stable channel pointer. So what you're saying with 

charm publish cs:~rharding/postgresql --channel stable

is this: charmstore, get me the postgresql revision that the stable pointer is pointing to and then set the pointer to that revision. Which is a no-op. 

With channels and pointers, there is no automatic resolving to the latest revision ... the latest revision is the revision that is pointed to by the channel pointer. Specifying revision is actually a must if you want to move the pointer. 

Now, we could provide option like:
charm publish cs:~rharding/postgresql --latest --channel stable 
But it is not clear what latest means here. Do you want to publish latest unpublished revision? Latest development revision? Development revision pointed to with development pointer?
Specifying revision is the cleanest way, but we can explore other options.

**Comment by urosj** [comment]
Revision is always required with publish.
