### ISSUE TITLE
new release?

### ISSUE THREAD

**Issue by chenrui333** [juju/charmstore-client#218]
I wonder if there is going to be a new release for the recent go modules build migration (last release was four years back). 

Also it would improve the current [homebrew formula](https://github.com/Homebrew/homebrew-core/blob/master/Formula/charm.rb). Thanks!

**Comment by mhilton** [comment]
Hi @chenrui333 I have tagged the latest version for release. Do you need anything else?

**Comment by chenrui333** [comment]
@mhilton thank you, if possible, can you also make it as latest release? Thanks!!

**Comment by chenrui333** [comment]
For the new build 2.5.0 on the homebrew side, I found a bug with the current go.mod, I will submit a fix in a minute.

**Comment by mhilton** [comment]
@chenrui333 is the v2.5.1 release working for you now?

**Comment by chenrui333** [comment]
works well for me, thanks for creating those releases. Close this issue now.
