### ISSUE TITLE
'charm show' fails for bundles

### ISSUE THREAD

**Issue by kwmonroe** [juju/charmstore-client#23]
I would like to use 'charm show' on bundles, but get this:

```
$ charm show mediawiki-single
ERROR cannot get metadata from /mediawiki-single/meta/any?include=archive-size&include=archive-upload-time&include=bundle-machine-count&include=bundle-metadata&include=bundle-unit-count&include=bundles-containing&include=charm-actions&include=charm-config&include=charm-metadata&include=charm-related&include=common-info&include=extra-info&include=hash&include=hash256&include=id&include=id-name&include=id-revision&include=id-series&include=id-user&include=manifest&include=perm&include=promulgated&include=published&include=resources&include=revision-info&include=stats&include=supported-series&include=tags&include=terms: bundles do not have resources
```

It would be nice if this command would return output similar to 'charm show' with charms, such as:
- upload-time (nice to have)
- common-info (bugs-url and homepage if relevant for bundles)
- id (including at least the name, revision, and user)
- manifest
- perm (if relevant for bundles)
- promulgated (if relevant for bundles)
- published
- revision-info (just bundle revs, though charm-revs per bundle rev would be nice to have)
- stats (nice to have)

**Comment by kwmonroe** [comment]
Well now I learned that 'charm show' does indeed work on bundles if you specify the right subset of data.  Turns out it just fails when trying to load 'resources'.

Stuff like 'charm show mediawiki-single  perm' along with other keys (besides resources) from `charm show --list` gets me everything I need for now.  De-prioritize this as appropriate!

**Comment by mitechie** [comment]
This is high priority since it tosses an error at a user running the
default command. The work around of specifying the data you want to get
around the error is a small workaround and should not lower the priority of
the issue.

**Comment by ericsnowcurrently** [comment]
This is a known issue do to incorrect handling of resources + bundles.  We are working on a fix.

**Comment by ericsnowcurrently** [comment]
FYI, the fix will be to the charm store and will require a redeploy of the charm store.
