### ISSUE TITLE
trailing slash on bundle url breaks cli

### ISSUE THREAD

**Issue by dpb1** [juju/charmstore-client#40]
```
dpb@helo:build[0]$ charm push landscape-dense-maas cs:~landscape/bundle/landscape-dense-maas/
error: invalid charm or bundle id "cs:~landscape/bundle/landscape-dense-maas/": charm or bundle URL has invalid form: "cs:~landscape/bundle/landscape-dense-maas/"
```

 removing the trailing slash allows things to proceed.

**Comment by rogpeppe** [comment]
I'm not sure this is worth changing the URL format for. Charm URLs should not have trailing slashes - just don't put them there. Changing the URL format can potentially have forward/backward compatibility issues when tools at different versions interoperate, so I'd prefer to reserve doing that for more major problems/features.
