### ISSUE TITLE
'charm login' gets an oauth token, fails to use it

### ISSUE THREAD

**Issue by stub42** [juju/charmstore-client#51]
(moved from charm-tools)

charm login successfully creates an oauth token (I can see it in the SSO web interface), but seems incapable of actually using it.

$ charm login
Login to Ubuntu SSO
Press return to select a default value.
E-Mail: stuart@stuartbishop.net
Password:
Two-factor auth (Enter for none): 123456
ERROR login failed: invalid OAuth credentials

This is not Issue #41, as the work around (logging into the charm store) does not help.

**Comment by urosj** [comment]
@stub42 And this is still after you've logged in through jujucharms.com there?

**Comment by stub42** [comment]
Yes. I've repeated this several times, confirming that I'm logged to jujucharms.com before trying 'charm login', and then logging out and relogging in again to jujucharms.com to see if the oauth token starts working (it doesn't, and 'charm login' just repeats the ERROR message without asking for credentials)

**Comment by urosj** [comment]
@stub42 what is your LP nickname, so that we can trace you down in logs/db? Is it stub42?

**Comment by stub42** [comment]
@urosj stub

**Comment by mhilton** [comment]
@stub42 could you please run the script at http://paste.ubuntu.com/15968079/ and report the results, it'll help identify where the problem is occurring.

**Comment by stub42** [comment]
Verify token with Ubuntu SSO
OK
{u'is_valid': False, u'account_verified': False}
()
Verify token with jujucharms.com
Internal Server Error
{"message":"invalid OAuth credentials"}

**Comment by mhilton** [comment]
@stub42 Sorry for not looking at this sooner, but somehow you are getting a token that is not validating against Ubuntu SSO. Being as the token comes from Ubuntu SSO this is very strange. Potentially this is an Ubuntu SSO bug, although I'm more inclined to think it isn't. Your token will be stored in $HOME/.local/share/juju/store-usso-token. Could you have a quick look at it and see if there are any characters in there that could end up being encoded incorrectly when URL escaped?

**Comment by stub42** [comment]
There are no unusual characters in there - it all looks to be clean alpha numerics. The trigger is likely that I have a very, very old account and there might be some assumptions being made that are not true for me. Which I could fix, if I knew what they were. I've looked at the database though and the important points I'm aware of all look fine.

**Comment by stub42** [comment]
Its an SSO issue. src/identityprovider/auth.py assumes all openid identifiers are 7 characters in length, and mine isn't.

**Comment by stub42** [comment]
Just me and a few bots affected.
