### ISSUE TITLE
Charms download to wrong directory

### ISSUE THREAD

**Issue by pmatulis** [juju/charmstore-client#55]
According to the [documentation](https://jujucharms.com/docs/devel/tools-charm-tools) this directory should be created and contain the charm files:

`~/charms/wordpress`

when this command is used:

`charm pull wordpress ~/charms/`

But what happens is this:

`head -3 ~/charms/README.md`
`# Overview`

`WordPress is a powerful blogging platform written in PHP. This charm aims to`

If I try to do it again for another charm naturally i get told 'ERROR directory "/home/ubuntu/charms/" already exists' so the specified dir name is effectively an alternate name for the charm's dir. A user needs to therefore cd to a central charm repository dir prior to downloading.

**Comment by jrwren** [comment]
I cannot reproduce this. `charm pull cs:somecharm` downloads the charm to a directory named `somecharm`.

**Comment by pmatulis** [comment]
Try specifying a directory like I did.

**Comment by jrwren** [comment]
This is by design.

As `charm help pull` says:
```
The pull command downloads a copy of a charm or bundle
from the charm store into a local directory.
If the directory is unspecified, the directory
will be named after the charm or bundle
```

The optional target directory is the target of the charms files, not the target directory of a directory for the charm files.

**Comment by pmatulis** [comment]
OK
