### ISSUE TITLE
'charm push' fails to ignore ignored files

### ISSUE THREAD

**Issue by stub42** [juju/charmstore-client#62]
'charm push' blissfully uploads the target directory, including all my temporary files and secrets.

It should not do this. Charms composed using 'charm build' contain a manifest which should be used. Non composed charms should honour .gitignore and/or .bzrignore.

**Comment by frankban** [comment]
I am not sure charm push should honor vcs ignored files. What if my charm is code generated and the vcs ignored files are exactly what I need/want to push? The charm package does not make any assumption on manifest files and other artifacts, and currently when creating a charm archive the only exluded files/dirs are hidden ones. See https://github.com/juju/charm/issues/201
Anyway, this is not really related to the charm client, the current behavior is implemented in https://github.com/juju/charm/tree/v6-unstable
