### ISSUE TITLE
Cannot push & publish

### ISSUE THREAD

**Issue by stub42** [juju/charmstore-client#64]
Currently, pushing and publishing are separate actions requiring cut-and-paste to complete (or an overly confusing shell command).

Could 'charm push' also accept the --channel parameter, which causes it to publish to the provided channel after the push?

**Comment by urosj** [comment]
Given that we're introducing more channels, unless requested by most charmers, we'll not allow such behaviour.

**Comment by stub42** [comment]
I don't understand the rationale that adding more channels makes this undesirable behaviour. More channels just makes this problem worse. I'm not suggesting removing the publish command. I'm suggesting adding an argument to the push command so it performs the publish after a successful push.

The goal here is to be able to write makefile rules that publish a branch to a channel in the store. More channels just makes the problem worse, as you end up with more unmaintainable techdebt stanzas like this:

``` make
publish-dev: build-dev
        cd $(BUILD_DIR) \
            && export rev=`charm push . $(CHARM_STORE_URL) 2>&1 \
                | tee /dev/tty | grep url: | cut -f 2 -d ' '` \
            && git tag -f -m "$$rev" `echo $$rev | tr -s '~:/' -` \
            && charm publish -c development $$rev
```
