### ISSUE TITLE
"charm show" shows way too much information

### ISSUE THREAD

**Issue by panlinux** [juju/charmstore-client#91]
I did a "charm show <mycharm>" to find out the ACLs it currently has, and was greeted by hundreds and hundreds of lines pertaining to other charms under the "charm-related" key:

> charm-related:
>   Provides:
>     pgsql:
>     - Id: cs:~alexlist/precise/pgbouncer-0
>     - Id: cs:~alexlist/precise/pgbouncer-1
>     - Id: cs:~alexlist/precise/postgresql-0
> ...

Try it for fun:
`charm show cs:~ahasenack/landscape-server`

It also shows all the files from the charm. I think that is way too much information and needs a good cleanup.

**Comment by marcoceppi** [comment]
currently charmstore-client lists all available keys when run, `charm show cs:~ahasenack/landscape-server perm` would just show the perms. Likewise: `charm show cs:~ahasenack/landscape-server perm id` would show the id and perm field. There's currently not a notion of `exclude` for charm show.

Do you have a recommendation for what the UX would be for that? Or what the default fields would be? For me, given I'm a developer, I don't mind having too much information esp after learning how to filter. The charm command won't typically be used by consumers of Juju, as a target audience.

**Comment by panlinux** [comment]
On Fri, Sep 9, 2016 at 3:51 PM, Marco Ceppi notifications@github.com
wrote:

> currently charmstore-client lists all available keys when run, charm show
> cs:~ahasenack/landscape-server perm would just show the perms. Likewise: charm
> show cs:~ahasenack/landscape-server perm id would show the id and perm
> field. There's currently not a notion of exclude for charm show.
> 
> Do you have a recommendation for what the UX would be for that? Or what
> the default fields would be? For me, given I'm a developer, I don't mind
> having too much information esp after learning how to filter. The charm
> command won't typically be used by consumers of Juju, as a target audience.

I don't see how this is useful by default, for example:

charm-related:
  Provides:
    pgsql:
    - Id: cs:~alexlist/precise/pgbouncer-0
(...)
(all revisions of every single charm that ever connected to pgsql)
(207 lines)
    rabbitmq:
    - Id: cs:~alai/trusty/calico-rabbitmq-server-0
    - Id: cs:~alai/trusty/calico-rabbitmq-server-1
(all revisions of every single charm that ever connected to rabbitmq)
(1494 lines)
  Requires:
    block-storage:
(51 lines)
    http:
(950 lines)
(...)

It shows every single charm revision that ever had those
interfaces/relations.

**Comment by mitechie** [comment]
I know the blast of info is something we've accepted for now since you can filter, however I think that the point that showing every revision of every charm that can connect to a relation endpoint is overkill information. I think we should only show the latest revision as a helpful "things you could connect" tool and leave it to testing/etc to find out if older revisions of a charm will work. I don't know why a user would be looking for that information here anyway.

**Comment by urosj** [comment]
We'll work on a summary version and only show latest revisions for each channel. We'll provide full info only if requested.

**Comment by urosj** [comment]
This has been updated, current information is:

```
uros$ charm show mysql
MySQL is a fast, stable and true multi-user, multi-threaded SQL database

Name            mysql
Owner           mysql-charmers
Revision        55
Supported Series    trusty, precise
Tags            databases, openstack
Subordinate     false
Promulgated     true
Home page       https://github.com/marcoceppi/charm-mysql
Bugs url        https://github.com/marcoceppi/charm-mysql/issues
Read            mysql-charmers, everyone
Write           charmers

CHANNEL         CURRENT
stable          true        
```

You can still see all the info by providing --all flag. 

PS: output is aligned into two columns in the CLI.

**Comment by marcoceppi** [comment]
Any reason Supported Series isn't just Series

**Comment by mhilton** [comment]
This is in the released snap
