### ISSUE TITLE
'charm pull' gives unhelpful error when terms are required

### ISSUE THREAD

**Issue by bac** [juju/charmstore-client#97]
Doing the following:

`$ charm pull cs:~ibmcharmers/trusty/ibm-http-5`

Gives the error:
```
ERROR cannot get archive: cannot get discharge from "https://api.jujucharms.com/terms": third party refused discharge: term agreement required: ibm-http-server/2 ibm-http-wct/1
```

Since the user is exercising the `charm` tool, the first thing to do would be to look at `charm help`, which leads nowhere.

Of course the correct thing is to agree to the terms using a different tool `juju agree`.

The error message should provide some guidance to the user.  @cmars says in analogous situations juju actually prints something helpful. Perhaps that messaging can be used as a guide.

**Comment by alesstimec** [comment]
Should be improved when https://github.com/juju/charmstore-client/pull/98 lands
