### ISSUE TITLE
charm attach should provide progress information

### ISSUE THREAD

**Issue by marcoceppi** [juju/charmstore-client#99]
_From @wwwtyro on November 17, 2016 15:37_

## Checklist

 - [ ] Confirmed this is an issue with charm-tools, not charmstore-client
 - [X] Provide versions of tools used
 - [X] Described the feature or ways to replicate the issue

## What version am I running?

I ran the following command: `charm version` and got the following ouput:

```
charm 2.2.0-0ubuntu1~ubuntu16.04.1~ppa2
charm-tools 2.1.8
```

I am using: Ubuntu 16.04

## Issue/Feature

It'd be nice if `charm attach` displayed upload progress.

### I expect/expected the following

`[=================>                   ] 60%`

### What I got

Literally nothing. Zero feedback until the upload is complete, which can take a while depending on uplink/filesize. Is it frozen? You don't know!

![giphy](https://cloud.githubusercontent.com/assets/929443/20395670/57a1104a-aca9-11e6-8c97-832e72c51f9a.gif)

_Copied from original issue: juju/charm-tools#285_

**Comment by marcoceppi** [comment]
_From @johnsca on November 18, 2016 17:59_

`charm attach` is implemented in https://github.com/juju/charmstore-client

**Comment by wwwtyro** [comment]
Just saw this working, thanks for the fix! I think this can be closed now.
